"""Public V3 machine-learning dataset contracts."""

from src.ml.contracts import (
    MLDataset,
    MLDatasetAlignmentError,
    MLDatasetAudit,
    MLDatasetConfig,
    MLDatasetDuplicateKeyError,
    MLDatasetError,
    MLDatasetSchemaError,
    MLDatasetValueError,
)
from src.ml.dataset import MLDatasetBuilder
from src.ml.models import (
    ElasticNetModelAdapter,
    ElasticNetModelConfig,
    HistGradientBoostingModelAdapter,
    HistGradientBoostingModelConfig,
    ModelConfigError,
    ModelDataError,
    ModelError,
    ModelFeatureMismatchError,
    ModelFeatureImportanceUnavailableError,
    ModelFitAudit,
    ModelFitError,
    ModelNotFittedError,
    ModelParameterSpec,
    ModelPredictionError,
    ModelRegistry,
    ModelRegistryError,
    RegressionModelAdapter,
    RidgeModelAdapter,
    RidgeModelConfig,
    create_default_model_registry,
)
from src.ml.splitting import (
    WalkForwardConfig,
    WalkForwardConfigError,
    WalkForwardDataError,
    WalkForwardError,
    WalkForwardInsufficientHistoryError,
    WalkForwardIntegrityError,
    WalkForwardPlan,
    WalkForwardSplit,
    WalkForwardSplitter,
)

__all__ = [
    "ElasticNetModelAdapter",
    "ElasticNetModelConfig",
    "MLDataset",
    "HistGradientBoostingModelAdapter",
    "HistGradientBoostingModelConfig",
    "MLDatasetAlignmentError",
    "MLDatasetAudit",
    "MLDatasetBuilder",
    "MLDatasetConfig",
    "MLDatasetDuplicateKeyError",
    "MLDatasetError",
    "MLDatasetSchemaError",
    "MLDatasetValueError",
    "ModelConfigError",
    "ModelDataError",
    "ModelError",
    "ModelFeatureMismatchError",
    "ModelFitAudit",
    "ModelFeatureImportanceUnavailableError",
    "ModelFitError",
    "ModelNotFittedError",
    "ModelParameterSpec",
    "ModelPredictionError",
    "ModelRegistry",
    "ModelRegistryError",
    "RegressionModelAdapter",
    "RidgeModelAdapter",
    "RidgeModelConfig",
    "WalkForwardConfig",
    "WalkForwardConfigError",
    "WalkForwardDataError",
    "WalkForwardError",
    "WalkForwardInsufficientHistoryError",
    "WalkForwardIntegrityError",
    "WalkForwardPlan",
    "WalkForwardSplit",
    "WalkForwardSplitter",
    "create_default_model_registry",
]
